site_name: Aiming Documentation
docs_dir: 'src'
site_dir: 'docs'
nav:
  - Home: ./index.md
  - Examples:
    - Index: ./examples/index.md
    - Namecall: ./examples/namecall.md
    - Aim Lock: ./examples/aimlock.md
  - Aiming:
    - Update FOV: ./aiming/updatefov.md
    - Get Closest Target Part To Cursor: ./aiming/getclosesttargetparttocursor.md
    - Get Closest To Cursor: ./aiming/getclosesttocursor.md
    - Selected: ./aiming/selected.md
    - Settings: ./aiming/settings.md
    - Signals: ./aiming/signals.md
    - Modules:
      - Index: ./aiming/modules/index.md
      - Utilities:
        - Calculate Chance: ./aiming/modules/utilities/calculatechance.md
        - Camera Look At: ./aiming/modules/utilities/cameralookat.md
        - Character: ./aiming/modules/utilities/character.md
        - Is Part Visible: ./aiming/modules/utilities/ispartvisible.md
        - Raycast: ./aiming/modules/utilities/raycast.md
        - Set Camera CFrame: ./aiming/modules/utilities/setcameracframe.md
      - Ignored:
        - Ignore Player: ./aiming/modules/ignored/ignoreplayer.md
        - Ignore Team: ./aiming/modules/ignored/ignoreteam.md
        - Is Ignored: ./aiming/modules/ignored/isignored.md
        - Is Ignored Team: ./aiming/modules/ignored/isignoredteam.md
        - Team Check: ./aiming/modules/ignored/teamcheck.md
        - Unignore Player: ./aiming/modules/ignored/unignoreplayer.md
        - Unignore Team: ./aiming/modules/ignored/unignoreteam.md
      - Checks:
        - Custom: ./aiming/modules/checks/custom.md
        - Health: ./aiming/modules/checks/health.md
        - Is Available: ./aiming/modules/checks/isavailable.md
      - Beizer Curve:
        - Aim To: ./aiming/modules/beziercurve/aimto.md
        - Aim To B: ./aiming/modules/beziercurve/aimtob.md
        - Manager A: ./aiming/modules/beziercurve/managera.md
        - Manager B: ./aiming/modules/beziercurve/managerb.md
  - Beizer Manager:
    - Camera Mode: ./beizermanager/cameramode.md
    - Change Data: ./beizermanager/changedata.md
    - Constructor: ./beizermanager/constructor.md
    - Cubic Curve: ./beizermanager/cubiccurve.md
    - Do Control Point: ./beizermanager/docontrolpoint.md
    - Do Iteration: ./beizermanager/doiteration.md
    - Draw Path Func: ./beizermanager/drawpathfunc.md
    - Get Starting Point: ./beizermanager/getstartingpoint.md
    - Modify End Point: ./beizermanager/modifyendpoint.md
    - Mouse Mode: ./beizermanager/mousemode.md
    - Start: ./beizermanager/start.md
    - Stop: ./beizermanager/stop.md

theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences